### ISSUE TITLE
App crashes on Android 13 and above.

### ISSUE THREAD

**Issue by enstrapp-mobility** [huukhuong/react-native-zebra-rfid-barcode#2]
Hi, Thank you for the library. Everything works fine up to Android 11. On Android 13, the app crashes during launch with the error message "java.lang."SecurityException: AttributionSource needs the android.permission.BLUETOOTH_CONNECT permission. Please help me resolve this issue.

Thank you so much in advance.

**Comment by huukhuong** [comment]
Thanks for spotting the bug. I'll try to fix it when I have free time.

**Comment by efernandes-tech** [comment]
my fix:

![image](https://github.com/user-attachments/assets/642f5461-7f8c-4159-9ebb-e21596e9a861)

![image](https://github.com/user-attachments/assets/8e0253dd-155a-4466-88b3-aeb8429e2435)

![image](https://github.com/user-attachments/assets/5d38b805-7d18-446b-bc57-d868c08540b3)

**Comment by huukhuong** [comment]
[efernandes-tech](https://github.com/efernandes-tech) Thank you very much, this seems to be the best way currently. 
I planned to upgrade to the latest version of RFID SDK but was not successful. Your solution is very helpful, thanks for your contribution.

**Comment by Poojakrish** [comment]
I'm unable to fix this issue. Where should I write this piece of code?
Please update this in your package.

**Comment by huukhuong** [comment]
> I'm unable to fix this issue. Where should I write this piece of code? Please update this in your package.

Please check version 0.1.2 and README.md

**Comment by Poojakrish** [comment]
<img width="810" alt="Screenshot 2024-08-22 at 4 30 47 PM" src="https://github.com/user-attachments/assets/87380433-517f-464f-8b35-c5001c709534">

Please refer to the above image. I have added permission in MainActivity.java

Still, I'm getting the same error. Please refer to the to the below image.

<img width="1107" alt="Screenshot 2024-08-22 at 4 34 51 PM" src="https://github.com/user-attachments/assets/d4347351-2cec-4cc0-a718-357f4b53e0d5">

**Comment by huukhuong** [comment]
No bro, remove YourActivity class
onCreate function is child of MainActivity, not YourActivity

**Comment by Poojakrish** [comment]
Hi @huukhuong, Thank you very much.
I successfully installed the app on Android 13.

However, the scanner occasionally works and sometimes does not, and there is noise in the scanner. This happens across all Android versions.

How can I get this resolved?
